name: image_picker_gallery_camera
description: Flutter Package to Pick Image From Gallery or Camera. This Package supports picking image from Camera,Gallery and Both Camera abd Gallery.
version: 0.3.0
# author: Sayandh KP<kotlincodes@gmail.com,sayandhkp59@gmail.com>
homepage: https://github.com/kotlincodes/image_picker_gallery_camera

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

